version: '2.1'

services:
  vikings:
    image: vikings
    build: .
    env_file:
      - .env
    # environment:
    #   NODE_ENV: development
    ports:
      - 7626:8626
      - 9229:9229
    command: npm run start_debug
    # command: node --inspect=0.0.0.0:9229 server.js
